language: swift
os: osx
osx_image: xcode9.3

install: gem install xcpretty

jobs:
  include:
    - script:
      - set -o pipefail && xcodebuild test -project EnrichedText.xcodeproj -scheme EnrichedText-ios -destination "platform=iOS Simulator,name=iPhone X"  | xcpretty -c
      - bash <(curl -s https://codecov.io/bash) -J Tests-ios -F ios
    - script:
      - set -o pipefail && xcodebuild test -project EnrichedText.xcodeproj -scheme EnrichedText-mac -destination "platform=macos"  | xcpretty -c
      - bash <(curl -s https://codecov.io/bash) -J Tests-mac -F mac
    - script:
      - set -o pipefail && xcodebuild test -project EnrichedText.xcodeproj -scheme EnrichedText-tv -destination "platform=tvOS Simulator,name=Apple TV 4K"  | xcpretty -c
      - bash <(curl -s https://codecov.io/bash) -J Tests-tv -F tv
    - script:
      - set -o pipefail && xcodebuild build -project EnrichedText.xcodeproj -scheme EnrichedText-watch | xcpretty -c
    - script:
      - set -o pipefail && xcodebuild build -project EnrichedText.xcodeproj -scheme EnrichedText-ios-d | xcpretty -c
    - script:
      - set -o pipefail && xcodebuild build -project EnrichedText.xcodeproj -scheme EnrichedText-mac-d | xcpretty -c
    - script:
      - set -o pipefail && xcodebuild build -project EnrichedText.xcodeproj -scheme EnrichedText-tv-d | xcpretty -c
    - script:
      - set -o pipefail && xcodebuild build -project EnrichedText.xcodeproj -scheme EnrichedText-watch-d | xcpretty -c
